[package]
name = "fracmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.7"
image = "0.24.1"
num = "0.4.0"
num_cpus = "1.13.1"
rand = "0.8.5"
rayon = "1.5.1"
